//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_IS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhapHang
    {
        public int MaPhieuNhap { get; set; }
        public int MaSP { get; set; }
        public int SoLuongNhap { get; set; }
    
        public virtual PhieuNhapHang PhieuNhapHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
