//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_IS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonDichVu
    {
        public int MaHDDV { get; set; }
        public System.DateTime NgayGioTao { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string SoDienThoai { get; set; }
        public int MaNV { get; set; }
        public string TenVot { get; set; }
        public string LoaiDay { get; set; }
        public Nullable<System.DateTime> NgayGioLayVot { get; set; }
        public int SoKG { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string LoaiPhieu { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
