//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_IS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietHD_SanPham = new HashSet<ChiTietHD_SanPham>();
            this.ChiTietPhieuNhans = new HashSet<ChiTietPhieuNhan>();
            this.ChiTietPhieuNhapHangs = new HashSet<ChiTietPhieuNhapHang>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string LoaiSP { get; set; }
        public decimal GiaBan { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public System.DateTime NgayNhapKho { get; set; }
        public Nullable<int> ThoiGianBaoHanh { get; set; }
        public Nullable<int> MaTH { get; set; }
        public decimal GiaGoc { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHD_SanPham> ChiTietHD_SanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhan> ChiTietPhieuNhans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhapHang> ChiTietPhieuNhapHangs { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
    }
}
